# Generated by Django 3.2.8 on 2021-10-19 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20211019_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='names',
            new_name='name',
        ),
    ]
